# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: file-contents-sorter
      - id: mixed-line-ending
      # - id: no-commit-to-branch
      #   args:
      #     - --branch
      #     - master
      - id: pretty-format-json
        args:
        - --autofix
        - --indent=2
      - id: trailing-whitespace
        args:
        - --markdown-linebreak-ext=md

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v5.12.0
    hooks:
    - id: eslint

  - repo: https://github.com/pre-commit/mirrors-jshint
    rev: v2.9.7
    hooks:
    - id: jshint

  - repo: https://github.com/digitalpulp/pre-commit-php
    rev: 1.3.0
    hooks:
    - id: php-lint
    # - id: php-cbf
    # - id: php-cs-fixer
    - id: php-cs
    - id: php-unit

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 1.10.3
    hooks:
      - id: forbid-binary
      - id: git-check

  # - repo: https://github.com/Lucas-C/pre-commit-hooks.git
  #   rev: v1.1.6
  #   hooks:
  #     - id: remove-crlf
  #     - id: remove-tabs

  - repo: https://github.com/chriskuehl/puppet-pre-commit-hooks.git
    rev: v2.0.2
    hooks:
    - id: puppet-validate
    - id: erb-validate
    - id: epp-validate
    - id: puppet-lint
      args:
      - --fail-on-warnings

  - repo: https://github.com/ansible/ansible-lint.git
    rev: v4.0.1
    hooks:
      - id: ansible-lint

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.14.0
    hooks:
      - id: yamllint

  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v1.0.0
    hooks:
      - id: docker-compose-check

  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
    - id: dockerfilelint
