#!/bin/bash

PROJECT_DIR="${PWD}"
RESULT=-1

check()
{
    ant check; RESULT=$?
    return ${RESULT}
}

if which ant > /dev/null 2>&1 && [ -e "${PROJECT_DIR}"/build.xml ]; then
    check; RESULT=$?
else
    RESULT=0
fi

exit ${RESULT}
