#!/bin/bash

PROJECT_DIR="${PWD}"
RESULT=-1

check()
{
    if composer list | grep "verify" > /dev/null 2&>1; then
        composer run verify ; RESULT=$?
    elif composer list | grep "test" > /dev/null 2&>1; then
        composer test ; RESULT=$?
    fi

    return ${RESULT}
}

if which composer > /dev/null 2>&1 && [ -e "${PROJECT_DIR}"/composer.lock ]; then
    check; RESULT=$?
else
    RESULT=0
fi

exit ${RESULT}
