#!/bin/bash

source "${GIT_DIR}"/hooks/config.sh

FILES="${GIT_DIR}"/files.$$
MOVE=1
OUTFILE="${GIT_DIR}"/tags.$$

build()
{
    case "${1}" in
        'php')
            find "${PROJECT_DIR}" -type f \( -iname '*.php' -a ! -iname '*test.php' \) > "${FILES}"
            ;;
    esac

    ctags --languages="${1}" -L "${FILES}" -f "${OUTFILE}" > /dev/null 2>&1
    MOVE=$?

    if [ ${MOVE} -eq 0 ]; then
        cp "${OUTFILE}" "${GIT_DIR}"/tags
    fi

    rm --force "${FILES}" "${OUTFILE}"
}

if which ctags > /dev/null 2>&1; then
    trap "rm --force \"${FILES}\" \"${OUTFILE}\"" EXIT

    build "${1}"
fi
