#!/bin/bash

PROJECT_DIR="${PWD}"
RESULT=-1

check()
{
    mvn test integration-test; RESULT=$?
    return ${RESULT}
}

if which mvn > /dev/null 2>&1 && [ -r "${PROJECT_DIR}"/pom.xml ]; then
    check; RESULT=$?
else
    RESULT=0
fi

exit ${RESULT}
