#!/usr/bin/env python3

from languages.java import Mvn
from languages.make import Make
from languages.javascript import Npm
from languages.php import Composer



def main():
    Composer().postMerge()
    Make().postMerge()
    Mvn().postMerge()
    Npm().postMerge()



if __name__ == "__main__":
    main()
