#!/usr/bin/env python3

from languages.java import Mvn
from languages.javascript import Npm
from languages.php import Composer


def main():
    Composer().post_merge()
    Mvn().post_merge()
    Npm().post_merge()


if __name__ == "__main__":
    main()
