#!/usr/bin/env python3

from languages.java import Mvn
from languages.make import Make
from languages.javascript import Npm
from languages.php import Composer



def main():
    Composer().postCheckout()
    Make().postCheckout()
    Mvn().postCheckout()
    Npm().postCheckout()



if __name__ == "__main__":
    main()
