#!/usr/bin/env python3

from languages.java import Mvn
from languages.javascript import Npm
from languages.php import Composer


def main():
    Composer().post_checkout()
    Mvn().post_checkout()
    Npm().post_checkout()


if __name__ == "__main__":
    main()
